export const treesData = [
    {
        id: 1,
        name: "Birch",
        img: "trees/birch_tree.png",
        price: 1200,
        inCart: false,
        quantity: 0,
        category: "Deciduous",
        soil: "moist",
        sun: "Semi shade",
        maxHeight: "13m",
        about: "The number one silver birch, hardy neat upright form with stunning pure white stem. A beautiful tree worthy of any landscape.",
        care: "Birch trees should should be pruned to maintain optimal health and a strong structure; remove lower hanging branches that interfere with walkways or driveways."
    },
    {
        id: 2,
        name: "Fir",
        img: "trees/fir_tree.jpg",
        price: 1350,
        inCart: false,
        quantity: 0,
        category: "Evergreen",
        soil: "moderate",
        sun: "Semi shade",
        maxHeight: "15m",
        about: "A handsome, blunt blue-tinged needles and a lovely fragrance. These same characteristics which make them popular Christmas trees also make them a good choice for a small garden if you are looking for a specimen tree to act as a focal point.",
        care: "Fir should be grown at a close enough spacing to restrict branch size, and a square spacing is better at controlling branch size than a rectangular spacing."
    },
    {
        id: 3,
        name: "Kauri",
        img: "trees/kauri_tree.jpg",
        price: 1980,
        inCart: false,
        quantity: 0,
        category: "NZ Native",
        soil: "moderate",
        sun: "Full sun",
        maxHeight: "60m",
        about: "The New Zealand kauri is the largest tree in the Agathis genus and the only Agathis species native to New Zealand",
        care:"Kauri growth requires high light levels but can tolerate low soil nutrient levels. "
    },
    {
        id: 4,
        name: "Oak",
        img: "trees/oak_tree.jpg",
        price: 1250,
        inCart: false,
        quantity: 0,
        category: "Deciduous",
        soil: "moist",
        sun: "Full sun",
        maxHeight: "25m",
        about: "Great for providing shade in summers. Low-maintenance trees that are easy to take care of in your home garden",
        care: "Oak trees prefer full sun and well-drained soil. They enjoy a natural change of seasons, with dry summers and moist winters. As long as you experience winter rainfall, you don't need to water oak trees in winter. "
   },
    {
        id: 5,
        name: "Pohutukawa",
        img: "trees/pohutukawa_tree.jpg",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "NZ Native",
        soil: "moderate",
        sun: "Semi shade",
        maxHeight: "20m",
        about: "Nicknamed the'New Zealand Christmas Tree' due to its bright flowers that resemble tree decor. It is prized as a beautiful ornamental tree by many gardeners.",
        care: "Water the tree once every two or three days in the first growing season. This will help the tree remain strong and establish itself faster."
    },
    {
        id: 6,
        name: "Pin Oak",
        img: "https://www.theplantstore.co.nz/files/15704_20140919121411-1411085651_postcard.jpg",
        price: 1045,
        inCart: false,
        quantity: 0,
        category: "Deciduous",
        soil: "moist",
        sun: "Moderate Sun",
        maxHeight: "10",
        about: "It has a growth rate of 60cm a year and is one of the fastest growing oak trees. It is tolerant of wet soils and a great home for birds.",
        care: "Pin oaks can develop iron chlorosis if soil pH is too high or alkaline, which causes leaves to turn yellow and drop prematurely. To correct this, use acidic or iron rich soil amendments or tree fertilizers."
   },
    {
        id: 7,
        name: "Verdale Olive",
        img: "https://greenleafnurseries.co.nz/wp-content/uploads/2013/06/olive-verdale-500.jpg",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "Evergreen",
        soil: "moist",
        sun: "Full sun",
        maxHeight: "5",
        about: "Grows tall and upright with thinned branching. Leaves are green/silver in colour and the bark is a light grey. Verdale produces medium sized, good quality olives.",
        care: "This tree orginiatese from the mediterranean and would not do well in colder environments of the South Island."
   },
    {
        id: 8,
        name: "Henkel Yellowwood",
        img: "https://www.icontrees.co.nz/ic/2859129367/Podocarpus%20Henkelii%20tree.JPG",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "Evergreen",
        soil: "moist",
        sun: "Moderate sun",
        maxHeight: "8",
        about: "A medium to large tree with dense, lush green foliage which is narrow and thin. Very slow growing and mildly drought tolerant.",
        care: "Requires light pruning and shelter from strong winds."    },
    {
        id: 9,
        name: "Japanese Maple",
        img: "http://cdn.shopify.com/s/files/1/0059/8835/2052/products/Red-Dragon-Japanese-Maple-50w_grande.jpg?v=1549677963",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "Deciduous",
        soil: "moderate",
        sun: "Semi shade",
        maxHeight: "5",
        about: "Beautiful tree in Autumn displaying brilliant scarlet tones and has attractive crimson coloured seeds.",
        care: "Most maples do not thrive in clay, heavy or poorly drained soils. These types of soils can lead to root rot and bring about disease.   In addition plants breathe through their roots and these soil types are not suitable for growth because they are low in oxygen required for good root growth."
    },
    {
        id: 10,
        name: "Japanese Cherry",
        img: "https://images-na.ssl-images-amazon.com/images/I/61S%2BLF61WSL._SX466_.jpg",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "Deciduous",
        soil: "moist",
        sun: "Full sun",
        maxHeight: "6",
        about: "Absolutely magnificent, it brightens our first spring days with abundant flowers in hues that range from white to pink.",
        care: "Very hardy to the cold and can survive in temperatures as low as -15°c to -20°c"
    },
    {
        id: 11,
        name: "Kowhai",
        img: "https://www.pncc.govt.nz/media/3130006/kowhai.jpg?anchor=center&mode=crop&width=1920&height=1080&rnd=131986076970000000&center=0.5,0.5",
        price: 1700,
        inCart: false,
        quantity: 0,
        category: "NZ Native",
        soil: "drained",
        sun: "Semi shade",
        maxHeight: "8",
        about: "Kōwhai are beautiful native trees iconic to New Zealand, with the gorgeous yellow flowers – while unofficial – being widely recognised as NZ’s native flower.",
        care: "Kōwhai grow in most soil types, however the speed is dependent on the quality. They tolerate dry soil and can also grow in clay soil however it will be slower than well-drained soil which they thrive in."
    }
];

export const clickedTree = {
    id: 1,
        name: "Birch",
        img: "trees/birch_tree.png",
        price: 1200,
        inCart: false,
        quantity: 0,
        category: "NZ Native",
        soil: "drained",
        sun: "Semi shade",
        maxHeight: "",
        about: "The number one silver birch, hardy neat upright form with stunning pure white stem. A beautiful tree worthy of any landscape.",
        care: "Birch trees should should be pruned to maintain optimal health and a strong structure; remove lower hanging branches that interfere with walkways or driveways."
}